apiVersion: apps/v1
kind: Deployment
metadata:
  name: laravel-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: laravel-app
  template:
    metadata:
      labels:
        app: laravel-app
    spec:
      containers:
        - name: laravel-app
          image: e00333ed4a0c857926ed1319b5c82bf7ca08132f45cec64f2c64f5257d6e557d/laravel-app:latest # Replace with your Docker image
          ports:
            - containerPort: 9000
