name: Laravel CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.2"
      - name: Install dependencies
        run: composer install
      - name: Create database
        run: touch database/database.sqlite
      - name: Run migrations
        run: php artisan migrate
      - name: Run tests
        run: php artisan test

      - name: Send email notification on failure
        if: failure()
        run: |
          curl -X POST -H "Content-Type: application/json" \
          -d '{"personalizations": [{"to": [{"email": "tongsreng@itc.edu.kh"}]}],"from": {"email": "noreply@github.com"},"subject": "Build Failed","content": [{"type": "text/plain", "value": "The build has failed."}]}' \
          https://api.sendgrid.com/v3/mail/send \
          -H "Authorization: Bearer ${{ secrets.SENDGRID_API_KEY }}"

          committer_email=$(git log -1 --pretty=format:'%ae')
          curl -X POST -H "Content-Type: application/json" \
          -d "{\"personalizations\": [{\"to\": [{\"email\": \"$committer_email\"}]}],\"from\": {\"email\": \"noreply@github.com\"},\"subject\": \"Build Failed\",\"content\": [{\"type\": \"text/plain\", \"value\": \"The build has failed.\"}]}" \
          https://api.sendgrid.com/v3/mail/send \
          -H "Authorization: Bearer ${{ secrets.SENDGRID_API_KEY }}"
